package com.nutrisphere.audit;
public enum AuditAction {
    REGISTER, LOGIN, LOGOUT, UPDATE_PROFILE, CHANGE_PASSWORD,
    CREATE, READ, UPDATE, DELETE, APPROVE, REJECT,
    UPLOAD_FILE, DOWNLOAD_FILE, ASSIGN_PATIENT, UNASSIGN_PATIENT,
    CREATE_DIET_PLAN, APPROVE_DIET_PLAN, UPDATE_DIET_PLAN,
    LOG_FOOD, LOG_WATER, RECORD_DEVIATION, RECORD_BARRIER,
    PLACE_ORDER, UPDATE_ORDER_STATUS
}
