export const ROLES = {
  PATIENT: "PATIENT",
  DIETITIAN: "DIETITIAN",
  DOCTOR: "DOCTOR",
  HOTEL: "HOTEL",
};

export const MEAL_TYPES = {
  BREAKFAST: "BREAKFAST",
  LUNCH: "LUNCH",
  DINNER: "DINNER",
  MORNING_SNACK: "MORNING_SNACK",
  EVENING_SNACK: "EVENING_SNACK",
  BEDTIME: "BEDTIME",
};

export const BARRIER_TYPES = {
  FOOD_UNAVAILABLE: "FOOD_UNAVAILABLE",
  TOO_EXPENSIVE: "TOO_EXPENSIVE",
  COOKING_PROBLEM: "COOKING_PROBLEM",
  TASTE: "TASTE",
  BUSY_SCHEDULE: "BUSY_SCHEDULE",
  SOCIAL_EVENT: "SOCIAL_EVENT",
  LACK_OF_APPETITE: "LACK_OF_APPETITE",
  OTHER: "OTHER",
};

export const DIET_PLAN_STATUS = {
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  ARCHIVED: "ARCHIVED",
};

export const ORDER_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  PREPARING: "PREPARING",
  READY: "READY",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};
