package com.nutrisphere.notification;
public enum NotificationType {
    ASSIGNMENT, CONSULTATION, DIET_PLAN_APPROVED, DIET_PLAN_UPDATED,
    FOOD_LOG_REMINDER, ADHERENCE_ALERT, BARRIER_ANALYSIS, RECOMMENDATION_REVIEW,
    ORDER_UPDATE, GENERAL
}
